version: "3.8"

services:
  db:
    container_name: postgres_database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - "54320:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5

  parse:
    depends_on:
      - db
    build:
      context: .
      dockerfile: DockerfilePARSER

  api:
    build:
      context: .
      dockerfile: DockerfileAPI
    ports:
        - "8000:8000"